on:
  schedule:
    - cron:  '0 * * * *' # every hour at minute zero 
  push:
    branches: main
  workflow_dispatch:

name: Update and Upload Crypto data 

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    permissions:
        contents: write
        
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3' # The R version to download (if necessary) and use.

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
            packages:
              any::jsonlite
              any::textshaping
              any::curl
              any::renv
              any::devtools
              any::tidyverse
              any::lubridate
              any::aws.s3
              any::httr
              any::rlang
              any::secret
              any::rvest
              any::xml2
              any::stringr
              any::anytime
              
      - name: Execute R Script
        env:
            access_key: ${{ secrets.ACCESS_KEY }}
            secret_key: ${{ secrets.SECRET_KEY }}
            aws_region: ${{ secrets.AWS_REGION }}
            bucket_name: ${{secrets.BUCKET_NAME}}
            
        run: |
            Rscript 04\ Pull\ Data.R
      
      - name: Render document
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: gfm
          path: README.qmd
          
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          
      - name: Commit
        run: |
          git add .
          git commit -m "Updated report"
          git push origin main
