on:
  schedule:
    - cron:  '0 10 * * *' # every day at midnight
  push:
    branches: main
  workflow_dispatch:

name: Update and Upload Crypto data 

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    permissions:
        contents: write
        
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1' # The R version to download (if necessary) and use.

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
            packages:
              renv@1.0.3
              devtools@2.4.4
              tidyverse@1.3.2
              lubridate@1.9.3
              aws.s3@0.3.20
              any::httr
              any::rlang
              any::secret
              
      - name: Execute R Script
        run: |
          cat("AWS_ACCESS_KEY_ID:", Sys.getenv("ACCESS_KEY"), "\n")
          cat("BUCKET_NAME:", Sys.getenv("AWS_REGION"), "\n")
          cat("BUCKET_NAME:", Sys.getenv("BUCKET_NAME"), "\n")
          cat("AWS_SECRET_ACCESS_KEY:", Sys.getenv("SECRET_KEY"), "\n")
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
      # Add the rest of your workflow steps here
      
       # run: |
       #     Rscript 02\ Pull\ Data.R
          
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          
